# Generated by Django 4.2.4 on 2023-09-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='selected_by',
        ),
    ]
