# Generated by Django 4.2.4 on 2023-09-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0002_remove_task_assigned_to_remove_task_selected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('waiting_for_confirmation', 'Waiting for Confirmation')], default='pending', max_length=40),
        ),
    ]
