# Generated by Django 4.2.4 on 2023-09-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0006_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(choices=[('do_not_disturb', 'Do Not Disturb'), ('call_back_later', 'Call Back Later'), ('not_interested', 'Not Interested'), ('not_reachable', 'Not Reachable'), ('interested', 'Interested')], max_length=20),
        ),
    ]
